/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/procaddress/ProcAddressEmitter.java on Tue Mar 11 04:20:01 CET 2014 ----! */


package com.jogamp.opengl.cg;

import java.nio.*;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import jogamp.common.os.MachineDescriptionRuntime;

import jogamp.opengl.*;
import com.jogamp.common.os.DynamicLookupHelper;
import com.jogamp.common.os.DynamicLibraryBundle;
import com.jogamp.opengl.cg.CgDynamicLibraryBundleInfo;
import java.security.PrivilegedAction;
import java.security.AccessController;

public class CGtechnique {

  StructAccessor accessor;

  private static final int mdIdx = MachineDescriptionRuntime.getStatic().ordinal();

  private static final int[] CGtechnique_size = new int[] { 0 /* ARMle_EABI */, 0 /* X86_32_UNIX */, 0 /* X86_64_UNIX */, 0 /* X86_32_MACOS */, 0 /* X86_32_WINDOWS */, 0 /* X86_64_WINDOWS */, 0 /* SPARC_32_SUNOS */  };

  public static int size() {
    return CGtechnique_size[mdIdx];
  }

  public static CGtechnique create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  public static CGtechnique create(java.nio.ByteBuffer buf) {
      return new CGtechnique(buf);
  }

  CGtechnique(java.nio.ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }
}
