/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/opengl/GLEmitter.java on Tue Mar 11 04:19:29 CET 2014 ----! */


package jogamp.opengl.windows.wgl;

import java.nio.*;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import jogamp.common.os.MachineDescriptionRuntime;

import java.util.*;
import javax.media.opengl.*;
import javax.media.opengl.fixedfunc.*;
import jogamp.opengl.*;

public class PGPU_DEVICE {

  StructAccessor accessor;

  private static final int mdIdx = MachineDescriptionRuntime.getStatic().ordinal();

  private static final int[] PGPU_DEVICE_size = new int[] { 0 /* ARMle_EABI */, 0 /* X86_32_UNIX */, 0 /* X86_64_UNIX */, 0 /* X86_32_MACOS */, 0 /* X86_32_WINDOWS */, 0 /* X86_64_WINDOWS */, 0 /* SPARC_32_SUNOS */  };

  public static int size() {
    return PGPU_DEVICE_size[mdIdx];
  }

  public static PGPU_DEVICE create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  public static PGPU_DEVICE create(java.nio.ByteBuffer buf) {
      return new PGPU_DEVICE(buf);
  }

  PGPU_DEVICE(java.nio.ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }
}
