/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/opengl/GLEmitter.java on Tue Mar 11 04:18:25 CET 2014 ----! */

package jogamp.opengl.es3;

import java.util.*;
import javax.media.opengl.*;
import javax.media.opengl.fixedfunc.*;
import jogamp.opengl.*;
import javax.media.opengl.GLBase;
import javax.media.opengl.GL;
import javax.media.opengl.GL2ES2;
import javax.media.opengl.GL2ES3;
import javax.media.opengl.GL3ES3;
import javax.media.opengl.GL4ES3;
import javax.media.opengl.GLES3;
import javax.media.opengl.GLArrayData;
import javax.media.opengl.GLUniformData;
import com.jogamp.common.nio.Buffers;
import com.jogamp.opengl.util.GLBuffers;
import java.io.PrintStream;
import com.jogamp.gluegen.runtime.ProcAddressTable;
import com.jogamp.common.util.SecurityUtil;

/**
 * This table is a cache of pointers to the dynamically-linkable C library.
 * @see ProcAddressTable
 */
public final class GLES3ProcAddressTable extends ProcAddressTable {

  /* pp */ long _addressof_glBufferData;
  /* pp */ long _addressof_glMapBuffer;
  /* pp */ long _addressof_glMapBufferRange;
  /* pp */ long _addressof_glUnmapBuffer;

  public GLES3ProcAddressTable(){ super(); }

  public GLES3ProcAddressTable(com.jogamp.gluegen.runtime.FunctionAddressResolver resolver){ super(resolver); }

  /* pp */ long _addressof_glActiveTexture;
  /* pp */ long _addressof_glAlphaFuncQCOM;
  /* pp */ long _addressof_glAttachShader;
  /* pp */ long _addressof_glBeginPerfMonitorAMD;
  /* pp */ long _addressof_glBeginQuery;
  /* pp */ long _addressof_glBeginTransformFeedback;
  /* pp */ long _addressof_glBindAttribLocation;
  /* pp */ long _addressof_glBindBuffer;
  /* pp */ long _addressof_glBindBufferBase;
  /* pp */ long _addressof_glBindBufferRange;
  /* pp */ long _addressof_glBindFramebuffer;
  /* pp */ long _addressof_glBindRenderbuffer;
  /* pp */ long _addressof_glBindSampler;
  /* pp */ long _addressof_glBindTexture;
  /* pp */ long _addressof_glBindTransformFeedback;
  /* pp */ long _addressof_glBindVertexArray;
  /* pp */ long _addressof_glBindVertexArrayOES;
  /* pp */ long _addressof_glBlendColor;
  /* pp */ long _addressof_glBlendEquation;
  /* pp */ long _addressof_glBlendEquationSeparate;
  /* pp */ long _addressof_glBlendFunc;
  /* pp */ long _addressof_glBlendFuncSeparate;
  /* pp */ long _addressof_glBlitFramebuffer;
  /* pp */ long _addressof_glBlitFramebufferANGLE;
  /* pp */ long _addressof_glBlitFramebufferNV;
  /* pp */ long _addressof_glBufferSubData;
  /* pp */ long _addressof_glCheckFramebufferStatus;
  /* pp */ long _addressof_glClear;
  /* pp */ long _addressof_glClearBufferfi;
  /* pp */ long _addressof_glClearBufferfv;
  /* pp */ long _addressof_glClearBufferiv;
  /* pp */ long _addressof_glClearBufferuiv;
  /* pp */ long _addressof_glClearColor;
  /* pp */ long _addressof_glClearDepthf;
  /* pp */ long _addressof_glClearStencil;
  /* pp */ long _addressof_glClientWaitSync;
  /* pp */ long _addressof_glColorMask;
  /* pp */ long _addressof_glCompileShader;
  /* pp */ long _addressof_glCompressedTexImage2D;
  /* pp */ long _addressof_glCompressedTexImage3D;
  /* pp */ long _addressof_glCompressedTexSubImage2D;
  /* pp */ long _addressof_glCompressedTexSubImage3D;
  /* pp */ long _addressof_glCopyBufferSubData;
  /* pp */ long _addressof_glCopyTexImage2D;
  /* pp */ long _addressof_glCopyTexSubImage2D;
  /* pp */ long _addressof_glCopyTexSubImage3D;
  /* pp */ long _addressof_glCopyTextureLevelsAPPLE;
  /* pp */ long _addressof_glCoverageMaskNV;
  /* pp */ long _addressof_glCoverageOperationNV;
  /* pp */ long _addressof_glCreateProgram;
  /* pp */ long _addressof_glCreateShader;
  /* pp */ long _addressof_glCullFace;
  /* pp */ long _addressof_glDebugMessageControl;
  /* pp */ long _addressof_glDebugMessageInsert;
  /* pp */ long _addressof_glDeleteBuffers;
  /* pp */ long _addressof_glDeleteFencesNV;
  /* pp */ long _addressof_glDeleteFramebuffers;
  /* pp */ long _addressof_glDeletePerfMonitorsAMD;
  /* pp */ long _addressof_glDeleteProgram;
  /* pp */ long _addressof_glDeleteQueries;
  /* pp */ long _addressof_glDeleteRenderbuffers;
  /* pp */ long _addressof_glDeleteSamplers;
  /* pp */ long _addressof_glDeleteShader;
  /* pp */ long _addressof_glDeleteSync;
  /* pp */ long _addressof_glDeleteTextures;
  /* pp */ long _addressof_glDeleteTransformFeedbacks;
  /* pp */ long _addressof_glDeleteVertexArrays;
  /* pp */ long _addressof_glDeleteVertexArraysOES;
  /* pp */ long _addressof_glDepthFunc;
  /* pp */ long _addressof_glDepthMask;
  /* pp */ long _addressof_glDepthRangef;
  /* pp */ long _addressof_glDetachShader;
  /* pp */ long _addressof_glDisable;
  /* pp */ long _addressof_glDisableDriverControlQCOM;
  /* pp */ long _addressof_glDisableVertexAttribArray;
  /* pp */ long _addressof_glDiscardFramebufferEXT;
  /* pp */ long _addressof_glDrawArrays;
  /* pp */ long _addressof_glDrawArraysInstanced;
  /* pp */ long _addressof_glDrawArraysInstancedANGLE;
  /* pp */ long _addressof_glDrawArraysInstancedNV;
  /* pp */ long _addressof_glDrawBuffers;
  /* pp */ long _addressof_glDrawBuffersIndexedEXT;
  /* pp */ long _addressof_glDrawElements;
  /* pp */ long _addressof_glDrawElementsInstanced;
  /* pp */ long _addressof_glDrawElementsInstancedANGLE;
  /* pp */ long _addressof_glDrawElementsInstancedNV;
  /* pp */ long _addressof_glDrawRangeElements;
  /* pp */ long _addressof_glEGLImageTargetRenderbufferStorageOES;
  /* pp */ long _addressof_glEGLImageTargetTexture2DOES;
  /* pp */ long _addressof_glEnable;
  /* pp */ long _addressof_glEnableDriverControlQCOM;
  /* pp */ long _addressof_glEnableVertexAttribArray;
  /* pp */ long _addressof_glEndPerfMonitorAMD;
  /* pp */ long _addressof_glEndQuery;
  /* pp */ long _addressof_glEndTilingQCOM;
  /* pp */ long _addressof_glEndTransformFeedback;
  /* pp */ long _addressof_glExtGetBufferPointervQCOM;
  /* pp */ long _addressof_glExtGetBuffersQCOM;
  /* pp */ long _addressof_glExtGetFramebuffersQCOM;
  /* pp */ long _addressof_glExtGetProgramBinarySourceQCOM;
  /* pp */ long _addressof_glExtGetProgramsQCOM;
  /* pp */ long _addressof_glExtGetRenderbuffersQCOM;
  /* pp */ long _addressof_glExtGetShadersQCOM;
  /* pp */ long _addressof_glExtGetTexLevelParameterivQCOM;
  /* pp */ long _addressof_glExtGetTexSubImageQCOM;
  /* pp */ long _addressof_glExtGetTexturesQCOM;
  /* pp */ long _addressof_glExtIsProgramBinaryQCOM;
  /* pp */ long _addressof_glExtTexObjectStateOverrideiQCOM;
  /* pp */ long _addressof_glFenceSync;
  /* pp */ long _addressof_glFinish;
  /* pp */ long _addressof_glFinishFenceNV;
  /* pp */ long _addressof_glFlush;
  /* pp */ long _addressof_glFlushMappedBufferRange;
  /* pp */ long _addressof_glFramebufferRenderbuffer;
  /* pp */ long _addressof_glFramebufferTexture2D;
  /* pp */ long _addressof_glFramebufferTexture2DMultisampleEXT;
  /* pp */ long _addressof_glFramebufferTexture2DMultisampleIMG;
  /* pp */ long _addressof_glFramebufferTexture3D;
  /* pp */ long _addressof_glFramebufferTextureLayer;
  /* pp */ long _addressof_glFrontFace;
  /* pp */ long _addressof_glGenBuffers;
  /* pp */ long _addressof_glGenFencesNV;
  /* pp */ long _addressof_glGenFramebuffers;
  /* pp */ long _addressof_glGenPerfMonitorsAMD;
  /* pp */ long _addressof_glGenQueries;
  /* pp */ long _addressof_glGenRenderbuffers;
  /* pp */ long _addressof_glGenSamplers;
  /* pp */ long _addressof_glGenTextures;
  /* pp */ long _addressof_glGenTransformFeedbacks;
  /* pp */ long _addressof_glGenVertexArrays;
  /* pp */ long _addressof_glGenVertexArraysOES;
  /* pp */ long _addressof_glGenerateMipmap;
  /* pp */ long _addressof_glGetActiveAttrib;
  /* pp */ long _addressof_glGetActiveUniform;
  /* pp */ long _addressof_glGetActiveUniformBlockName;
  /* pp */ long _addressof_glGetActiveUniformBlockiv;
  /* pp */ long _addressof_glGetActiveUniformsiv;
  /* pp */ long _addressof_glGetAttachedShaders;
  /* pp */ long _addressof_glGetAttribLocation;
  /* pp */ long _addressof_glGetBooleanv;
  /* pp */ long _addressof_glGetBufferParameteri64v;
  /* pp */ long _addressof_glGetBufferParameteriv;
  /* pp */ long _addressof_glGetBufferPointerv;
  /* pp */ long _addressof_glGetDebugMessageLog;
  /* pp */ long _addressof_glGetDriverControlStringQCOM;
  /* pp */ long _addressof_glGetDriverControlsQCOM;
  /* pp */ long _addressof_glGetError;
  /* pp */ long _addressof_glGetFenceivNV;
  /* pp */ long _addressof_glGetFloatv;
  /* pp */ long _addressof_glGetFragDataLocation;
  /* pp */ long _addressof_glGetFramebufferAttachmentParameteriv;
  /* pp */ long _addressof_glGetGraphicsResetStatus;
  /* pp */ long _addressof_glGetInteger64i_v;
  /* pp */ long _addressof_glGetInteger64v;
  /* pp */ long _addressof_glGetIntegeri_v;
  /* pp */ long _addressof_glGetIntegeri_vEXT;
  /* pp */ long _addressof_glGetIntegerv;
  /* pp */ long _addressof_glGetInternalformativ;
  /* pp */ long _addressof_glGetObjectLabelEXT;
  /* pp */ long _addressof_glGetObjectLabel;
  /* pp */ long _addressof_glGetObjectPtrLabel;
  /* pp */ long _addressof_glGetPerfMonitorCounterDataAMD;
  /* pp */ long _addressof_glGetPerfMonitorCounterInfoAMD;
  /* pp */ long _addressof_glGetPerfMonitorCounterStringAMD;
  /* pp */ long _addressof_glGetPerfMonitorCountersAMD;
  /* pp */ long _addressof_glGetPerfMonitorGroupStringAMD;
  /* pp */ long _addressof_glGetPerfMonitorGroupsAMD;
  /* pp */ long _addressof_glGetPointerv;
  /* pp */ long _addressof_glGetProgramBinary;
  /* pp */ long _addressof_glGetProgramInfoLog;
  /* pp */ long _addressof_glGetProgramiv;
  /* pp */ long _addressof_glGetQueryObjecti64vEXT;
  /* pp */ long _addressof_glGetQueryObjectivEXT;
  /* pp */ long _addressof_glGetQueryObjectui64vEXT;
  /* pp */ long _addressof_glGetQueryObjectuiv;
  /* pp */ long _addressof_glGetQueryiv;
  /* pp */ long _addressof_glGetRenderbufferParameteriv;
  /* pp */ long _addressof_glGetSamplerParameterfv;
  /* pp */ long _addressof_glGetSamplerParameteriv;
  /* pp */ long _addressof_glGetShaderInfoLog;
  /* pp */ long _addressof_glGetShaderPrecisionFormat;
  /* pp */ long _addressof_glGetShaderSource;
  /* pp */ long _addressof_glGetShaderiv;
  /* pp */ long _addressof_glGetString;
  /* pp */ long _addressof_glGetStringi;
  /* pp */ long _addressof_glGetSynciv;
  /* pp */ long _addressof_glGetTexParameterfv;
  /* pp */ long _addressof_glGetTexParameteriv;
  /* pp */ long _addressof_glGetTransformFeedbackVarying;
  /* pp */ long _addressof_glGetTranslatedShaderSourceANGLE;
  /* pp */ long _addressof_glGetUniformBlockIndex;
  /* pp */ long _addressof_glGetUniformIndices;
  /* pp */ long _addressof_glGetUniformLocation;
  /* pp */ long _addressof_glGetUniformfv;
  /* pp */ long _addressof_glGetUniformiv;
  /* pp */ long _addressof_glGetUniformuiv;
  /* pp */ long _addressof_glGetVertexAttribIiv;
  /* pp */ long _addressof_glGetVertexAttribIuiv;
  /* pp */ long _addressof_glGetVertexAttribfv;
  /* pp */ long _addressof_glGetVertexAttribiv;
  /* pp */ long _addressof_glGetnUniformfv;
  /* pp */ long _addressof_glGetnUniformiv;
  /* pp */ long _addressof_glHint;
  /* pp */ long _addressof_glInsertEventMarkerEXT;
  /* pp */ long _addressof_glInvalidateFramebuffer;
  /* pp */ long _addressof_glInvalidateSubFramebuffer;
  /* pp */ long _addressof_glIsBuffer;
  /* pp */ long _addressof_glIsEnabled;
  /* pp */ long _addressof_glIsFenceNV;
  /* pp */ long _addressof_glIsFramebuffer;
  /* pp */ long _addressof_glIsProgram;
  /* pp */ long _addressof_glIsQuery;
  /* pp */ long _addressof_glIsRenderbuffer;
  /* pp */ long _addressof_glIsSampler;
  /* pp */ long _addressof_glIsShader;
  /* pp */ long _addressof_glIsSync;
  /* pp */ long _addressof_glIsTexture;
  /* pp */ long _addressof_glIsTransformFeedback;
  /* pp */ long _addressof_glIsVertexArray;
  /* pp */ long _addressof_glIsVertexArrayOES;
  /* pp */ long _addressof_glLabelObjectEXT;
  /* pp */ long _addressof_glLineWidth;
  /* pp */ long _addressof_glLinkProgram;
  /* pp */ long _addressof_glObjectLabel;
  /* pp */ long _addressof_glObjectPtrLabel;
  /* pp */ long _addressof_glPauseTransformFeedback;
  /* pp */ long _addressof_glPixelStorei;
  /* pp */ long _addressof_glPolygonOffset;
  /* pp */ long _addressof_glPopDebugGroup;
  /* pp */ long _addressof_glPopGroupMarkerEXT;
  /* pp */ long _addressof_glProgramBinary;
  /* pp */ long _addressof_glProgramParameteri;
  /* pp */ long _addressof_glPushDebugGroup;
  /* pp */ long _addressof_glPushGroupMarkerEXT;
  /* pp */ long _addressof_glQueryCounterEXT;
  /* pp */ long _addressof_glReadBuffer;
  /* pp */ long _addressof_glReadBufferIndexedEXT;
  /* pp */ long _addressof_glReadBufferNV;
  /* pp */ long _addressof_glReadPixels;
  /* pp */ long _addressof_glReadnPixels;
  /* pp */ long _addressof_glReleaseShaderCompiler;
  /* pp */ long _addressof_glRenderbufferStorage;
  /* pp */ long _addressof_glRenderbufferStorageMultisample;
  /* pp */ long _addressof_glRenderbufferStorageMultisampleANGLE;
  /* pp */ long _addressof_glRenderbufferStorageMultisampleAPPLE;
  /* pp */ long _addressof_glRenderbufferStorageMultisampleIMG;
  /* pp */ long _addressof_glRenderbufferStorageMultisampleNV;
  /* pp */ long _addressof_glResolveMultisampleFramebufferAPPLE;
  /* pp */ long _addressof_glResumeTransformFeedback;
  /* pp */ long _addressof_glSampleCoverage;
  /* pp */ long _addressof_glSamplerParameterf;
  /* pp */ long _addressof_glSamplerParameterfv;
  /* pp */ long _addressof_glSamplerParameteri;
  /* pp */ long _addressof_glSamplerParameteriv;
  /* pp */ long _addressof_glScissor;
  /* pp */ long _addressof_glSelectPerfMonitorCountersAMD;
  /* pp */ long _addressof_glSetFenceNV;
  /* pp */ long _addressof_glShaderBinary;
  /* pp */ long _addressof_glShaderSource;
  /* pp */ long _addressof_glStartTilingQCOM;
  /* pp */ long _addressof_glStencilFunc;
  /* pp */ long _addressof_glStencilFuncSeparate;
  /* pp */ long _addressof_glStencilMask;
  /* pp */ long _addressof_glStencilMaskSeparate;
  /* pp */ long _addressof_glStencilOp;
  /* pp */ long _addressof_glStencilOpSeparate;
  /* pp */ long _addressof_glTestFenceNV;
  /* pp */ long _addressof_glTexImage2D;
  /* pp */ long _addressof_glTexImage3D;
  /* pp */ long _addressof_glTexParameterf;
  /* pp */ long _addressof_glTexParameterfv;
  /* pp */ long _addressof_glTexParameteri;
  /* pp */ long _addressof_glTexParameteriv;
  /* pp */ long _addressof_glTexStorage1D;
  /* pp */ long _addressof_glTexStorage2D;
  /* pp */ long _addressof_glTexStorage3D;
  /* pp */ long _addressof_glTexSubImage2D;
  /* pp */ long _addressof_glTexSubImage3D;
  /* pp */ long _addressof_glTextureStorage1D;
  /* pp */ long _addressof_glTextureStorage2D;
  /* pp */ long _addressof_glTextureStorage3D;
  /* pp */ long _addressof_glTransformFeedbackVaryings;
  /* pp */ long _addressof_glUniform1f;
  /* pp */ long _addressof_glUniform1fv;
  /* pp */ long _addressof_glUniform1i;
  /* pp */ long _addressof_glUniform1iv;
  /* pp */ long _addressof_glUniform1ui;
  /* pp */ long _addressof_glUniform1uiv;
  /* pp */ long _addressof_glUniform2f;
  /* pp */ long _addressof_glUniform2fv;
  /* pp */ long _addressof_glUniform2i;
  /* pp */ long _addressof_glUniform2iv;
  /* pp */ long _addressof_glUniform2ui;
  /* pp */ long _addressof_glUniform2uiv;
  /* pp */ long _addressof_glUniform3f;
  /* pp */ long _addressof_glUniform3fv;
  /* pp */ long _addressof_glUniform3i;
  /* pp */ long _addressof_glUniform3iv;
  /* pp */ long _addressof_glUniform3ui;
  /* pp */ long _addressof_glUniform3uiv;
  /* pp */ long _addressof_glUniform4f;
  /* pp */ long _addressof_glUniform4fv;
  /* pp */ long _addressof_glUniform4i;
  /* pp */ long _addressof_glUniform4iv;
  /* pp */ long _addressof_glUniform4ui;
  /* pp */ long _addressof_glUniform4uiv;
  /* pp */ long _addressof_glUniformBlockBinding;
  /* pp */ long _addressof_glUniformMatrix2fv;
  /* pp */ long _addressof_glUniformMatrix2x3fv;
  /* pp */ long _addressof_glUniformMatrix2x4fv;
  /* pp */ long _addressof_glUniformMatrix3fv;
  /* pp */ long _addressof_glUniformMatrix3x2fv;
  /* pp */ long _addressof_glUniformMatrix3x4fv;
  /* pp */ long _addressof_glUniformMatrix4fv;
  /* pp */ long _addressof_glUniformMatrix4x2fv;
  /* pp */ long _addressof_glUniformMatrix4x3fv;
  /* pp */ long _addressof_glUseProgram;
  /* pp */ long _addressof_glValidateProgram;
  /* pp */ long _addressof_glVertexAttrib1f;
  /* pp */ long _addressof_glVertexAttrib1fv;
  /* pp */ long _addressof_glVertexAttrib2f;
  /* pp */ long _addressof_glVertexAttrib2fv;
  /* pp */ long _addressof_glVertexAttrib3f;
  /* pp */ long _addressof_glVertexAttrib3fv;
  /* pp */ long _addressof_glVertexAttrib4f;
  /* pp */ long _addressof_glVertexAttrib4fv;
  /* pp */ long _addressof_glVertexAttribDivisor;
  /* pp */ long _addressof_glVertexAttribDivisorANGLE;
  /* pp */ long _addressof_glVertexAttribDivisorNV;
  /* pp */ long _addressof_glVertexAttribI4i;
  /* pp */ long _addressof_glVertexAttribI4iv;
  /* pp */ long _addressof_glVertexAttribI4ui;
  /* pp */ long _addressof_glVertexAttribI4uiv;
  /* pp */ long _addressof_glVertexAttribIPointer;
  /* pp */ long _addressof_glVertexAttribPointer;
  /* pp */ long _addressof_glViewport;
  /* pp */ long _addressof_glWaitSync;
  @Override
  protected boolean isFunctionAvailableImpl(String functionNameUsr) throws IllegalArgumentException  {
    final String functionNameBase = com.jogamp.gluegen.runtime.opengl.GLNameResolver.normalizeVEN(com.jogamp.gluegen.runtime.opengl.GLNameResolver.normalizeARB(functionNameUsr, true), true);
    final String addressFieldNameBase = "_addressof_" + functionNameBase;
    final int funcNamePermNum = com.jogamp.gluegen.runtime.opengl.GLNameResolver.getFuncNamePermutationNumber(functionNameBase);
    final java.lang.reflect.Field addressField = java.security.AccessController.doPrivileged(new java.security.PrivilegedAction<java.lang.reflect.Field>() {
        public final java.lang.reflect.Field run() {
            java.lang.reflect.Field addressField = null;
            for(int i = 0; i < funcNamePermNum; i++) {
                final String addressFieldName = com.jogamp.gluegen.runtime.opengl.GLNameResolver.getFuncNamePermutation(addressFieldNameBase, i);
                try {
                    addressField = GLES3ProcAddressTable.class.getDeclaredField( addressFieldName );
                    addressField.setAccessible(true); // we need to read the protected value!
                    return addressField;
                } catch (NoSuchFieldException ex) { }
            }
            return null;
        } } );

    if(null==addressField) {
      // The user is calling a bogus function or one which is not
      // runtime linked
      throw new RuntimeException(
          "WARNING: Address field query failed for \"" + functionNameBase + "\"/\"" + functionNameUsr +
          "\"; it's either statically linked or address field is not a known " +
          "function");
    } 
    try {
      return 0 != addressField.getLong(this);
    } catch (Exception e) {
      throw new RuntimeException(
          "WARNING: Address query failed for \"" + functionNameBase + "\"/\"" + functionNameUsr +
          "\"; it's either statically linked or is not a known " +
          "function", e);
    }
  }
  @Override
  public long getAddressFor(String functionNameUsr) throws SecurityException, IllegalArgumentException {
    SecurityUtil.checkAllLinkPermission();
    final String functionNameBase = com.jogamp.gluegen.runtime.opengl.GLNameResolver.normalizeVEN(com.jogamp.gluegen.runtime.opengl.GLNameResolver.normalizeARB(functionNameUsr, true), true);
    final String addressFieldNameBase = "_addressof_" + functionNameBase;
    final int  funcNamePermNum = com.jogamp.gluegen.runtime.opengl.GLNameResolver.getFuncNamePermutationNumber(functionNameBase);
    final java.lang.reflect.Field addressField = java.security.AccessController.doPrivileged(new java.security.PrivilegedAction<java.lang.reflect.Field>() {
        public final java.lang.reflect.Field run() {
            java.lang.reflect.Field addressField = null;
            for(int i = 0; i < funcNamePermNum; i++) {
                final String addressFieldName = com.jogamp.gluegen.runtime.opengl.GLNameResolver.getFuncNamePermutation(addressFieldNameBase, i);
                try {
                    addressField = GLES3ProcAddressTable.class.getDeclaredField( addressFieldName );
                    addressField.setAccessible(true); // we need to read the protected value!
                    return addressField;
                } catch (NoSuchFieldException ex) { }
            }
            return null;
        } } );

    if(null==addressField) {
      // The user is calling a bogus function or one which is not
      // runtime linked
      throw new RuntimeException(
          "WARNING: Address field query failed for \"" + functionNameBase + "\"/\"" + functionNameUsr +
          "\"; it's either statically linked or address field is not a known " +
          "function");
    } 
    try {
      return addressField.getLong(this);
    } catch (Exception e) {
      throw new RuntimeException(
          "WARNING: Address query failed for \"" + functionNameBase + "\"/\"" + functionNameUsr +
          "\"; it's either statically linked or is not a known " +
          "function", e);
    }
  }
} // end of class GLES3ProcAddressTable
